# Netlify "kitchen sink" example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml

localhost_development:
  backend:
    name: file-system
    api_root: /api

backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: home
    label: Home
    folder: content
    create: true
    fields:
      - { name: title, label: Title }

  - name: recording-studio
    label: Recording Studio
    folder: content
    create: true
    fields:
      - { name: title, label: Title }

  - name: listen-here
    label: Listen Here
    folder: content
    create: true
    fields:
      - { name: path, label: Path }

  - name: classes-workshops
    label: Classes Workshops
    folder: content
    create: true
    fields:
      - { name: path, label: Path }

  - name: george
    label: George R's Music
    folder: content
    create: true
    fields:
      - { name: path, label: Path }

  - name: lutherie-services
    label: Lutherie Services
    folder: content
    create: true
    fields:
      - { name: path, label: Path }

  - name: contact
    label: Contact
    folder: content
    create: true
    fields:
      - { name: path, label: Path }
