# Netlify "kitchen sink" example: https://github.com/netlify/netlify-cms/blob/master/dev-test/config.yml

localhost_development:
  backend:
    name: file-system
    api_root: /api

backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/home.md"
        name: "home"
        label: "Home"
        fields:
          - { name: title, label: Title }
          - { name: subTitle, label: Sub Title }
          - { name: quote, label: Main Quote }
          - { name: mailingListBlurb, label: Mailing-list Blurb }
          - { name: recentReleasesHeadline, label: Recent Releases Headline }
          - {
              name: recentReleases,
              label: Recent Releases,
              widget: list,
              fields:
                [
                  { name: description, label: Description, widget: markdown },
                  { name: image, label: Image, widget: image },
                ],
            }
          - {
              name: audioCallOut,
              label: Audio Callout,
              widget: list,
              fields:
                [
                  { name: description, label: Description, widget: markdown },
                  { name: embed, label: Audio Embed (YouTube / SoundCloud) },
                ],
            }
          - { name: templateKey, label: "Template Key", default: "home" }

      - file: "content/pages/studio.md"
        name: "studio"
        label: "Studio"
        fields:
          - { name: title, label: Title }
          - { name: subTitle, label: Sub Title }
          - { name: mainImage, label: Main Image, widget: image }
          - { name: features, label: Features, widget: markdown }
          - { name: testimonial, label: Testimonial, widget: text }
          - { name: moreInfo, label: More Info, widget: markdown }
          - { name: artists, label: Artists, widget: markdown }
          - { name: templateKey, label: "Template Key", default: "studio" }

      - file: "content/pages/listen-here.md"
        name: "listen-here"
        label: "Listen Here"
        fields:
          - { name: title, label: Title }
          - { name: subTitle, label: Sub Title }
          - {
              name: recordings,
              label: Recordings,
              widget: list,
              fields:
                [
                  {
                    name: description,
                    label: Description,
                    widget: markdown,
                    required: false,
                  },
                  { name: embed, label: Embed },
                ],
            }
          - { name: templateKey, label: "Template Key", default: "listen-here" }

      - file: "content/pages/classes.md"
        name: "classes"
        label: "Classes & Workshops"
        fields:
          - { name: title, label: Title }
          - { name: content, label: Content, widget: markdown }
          - { name: templateKey, label: "Template Key", default: "classes" }

      - file: "content/pages/gr-music.md"
        name: "gr-music"
        label: "George R's Music"
        fields:
          - { name: content, label: Content, widget: markdown }
          - { name: templateKey, label: "Template Key", default: "gr-music" }

      - file: "content/pages/lutherie.md"
        label: "Lutherie Services"
        name: "lutherie"
        fields:
          - { name: title, label: Title }
          - { name: content, label: Content, widget: markdown }
          - { name: templateKey, label: "Template Key", default: "lutherie" }

      - file: "content/pages/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - { name: title, label: Title }
          - { name: templateKey, label: "Template Key", default: "contact" }
